### ISSUE TITLE
Bug sur les RR après l'ajout d'extra rr dessus? 

### ISSUE THREAD

**Issue by gtedavid** [noftaly/MonkaBot#83]
**Décrivez le bug**

Impossible de changer la condition pour prendre le rôle
Et la condition semble disparaître quand on rajoute des rôles (paring) 

**Pour reproduire**

1. Le rr dans règles pour les promos ingé
2. le rr donne des rôles aux étudiants sans avoir le rôle parcours ingé

**Comportement attendu**

refus de donner le rôle......
**Screenshots**

**Comment by gtedavid** [comment]
les conditions des RR sont définitivement cassées

**Comment by noftaly** [comment]
Correction : les conditions de RR ne sont juste pas prises en comptes lors de la création. Il y a l'option, mais elle n'est pas utilisée dans le code.
C'est un fix rapide, je le ferai dès que j'ai le temps 😄

**Comment by gtedavid** [comment]
> Correction : les conditions de RR ne sont juste pas prises en comptes lors de la création. Il y a l'option, mais elle n'est pas utilisée dans le code. C'est un fix rapide, je le ferai dès que j'ai le temps 😄

Any news à ce sujet là ? 
Parce que ça veut dire qu'il faut que je refasse ça pour tous les menus que j'ai modifié....

**Comment by noftaly** [comment]
> Parce que ça veut dire qu'il faut que je refasse ça pour tous les menus que j'ai modifié....

tous les menus modifiés ? ???

j'ai juste dit que quand tu fais /reaction-role create et que tu mets l'option condition:
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/34779161/205090274-634cbc5c-ea40-4f91-9eb7-77dafaf517ce.png">
elle n'est pas prise en compte

Rien a voir avec les "menus modifiés", quand tu le modifies rien ne change la condition reste bien.

Par ailleurs j'ai pu tester avec des menus (les Promotions dans #règles) et ils ont actuellement tous bien leur condition, qui est fonctionnelle...
